# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Activity.destroy_all
Event.destroy_all
Coordinate.destroy_all

u1 = User.create(username: Faker::Internet.user_name, password: "password")
u2 = User.create(username: Faker::Internet.user_name, password: "password")
u3 = User.create(username: Faker::Internet.user_name, password: "password")
u4 = User.create(username: Faker::Internet.user_name, password: "password")
u5 = User.create(username: Faker::Internet.user_name, password: "password")
u6 = User.create(username: Faker::Internet.user_name, password: "password")
u7 = User.create(username: Faker::Internet.user_name, password: "password")
u8 = User.create(username: Faker::Internet.user_name, password: "password")
u9 = User.create(username: Faker::Internet.user_name, password: "password")
u10 = User.create(username: Faker::Internet.user_name, password: "password")
u11 = User.create(username: Faker::Internet.user_name, password: "password")
u12 = User.create(username: Faker::Internet.user_name, password: "password")
u13 = User.create(username: Faker::Internet.user_name, password: "password")
u14 = User.create(username: Faker::Internet.user_name, password: "password")
u15 = User.create(username: Faker::Internet.user_name, password: "password")
u16 = User.create(username: Faker::Internet.user_name, password: "password")
u17 = User.create(username: Faker::Internet.user_name, password: "password")
u18 = User.create(username: Faker::Internet.user_name, password: "password")
u19 = User.create(username: Faker::Internet.user_name, password: "password")
u20 = User.create(username: Faker::Internet.user_name, password: "password")
u21 = User.create(username: Faker::Internet.user_name, password: "password")
u22 = User.create(username: Faker::Internet.user_name, password: "password")
u23 = User.create(username: Faker::Internet.user_name, password: "password")
u24 = User.create(username: Faker::Internet.user_name, password: "password")
u25 = User.create(username: Faker::Internet.user_name, password: "password")

a1 = Activity.create(name: "Swimming")
a2 = Activity.create(name: "Surfing")
a3 = Activity.create(name: "Kicking")
a4 = Activity.create(name: "Biking")
a5 = Activity.create(name: "Unicycling")
a6 = Activity.create(name: "Birdwatching")
a7 = Activity.create(name: "Hunting")
a8 = Activity.create(name: "Climbing")

c1 = Coordinate.create(latitude: 37.774929, longitude: -122.419416)
c2 = Coordinate.create(latitude: 37.774238, longitude: -122.425182)
c3 = Coordinate.create(latitude: 37.786163, longitude: -122.405548)
c4 = Coordinate.create(latitude: 37.787113, longitude: -122.427692)
c5 = Coordinate.create(latitude: 37.762214, longitude: -122.442369)
c6 = Coordinate.create(latitude: 37.776685, longitude: -122.413445)
c7 = Coordinate.create(latitude: 37.779466, longitude: -122.419416)
c8 = Coordinate.create(latitude: 37.774332, longitude: -122.417994)
c9 = Coordinate.create(latitude: 37.783491, longitude: -122.426233)
c10 = Coordinate.create(latitude: 37.787256, longitude: -122.416320)
c11 = Coordinate.create(latitude: 37.785662, longitude: -122.427692)
c12 = Coordinate.create(latitude: 37.786408, longitude: -122.417092)
c13 = Coordinate.create(latitude: 37.787697, longitude: -122.427349)
c14 = Coordinate.create(latitude: 37.786747, longitude: -122.417693)
c15 = Coordinate.create(latitude: 37.778234, longitude: -122.421341)
c16 = Coordinate.create(latitude: 37.788205, longitude: -122.424088)
c17 = Coordinate.create(latitude: 37.790579, longitude: -122.416706)
c18 = Coordinate.create(latitude: 37.787493, longitude: -122.419324)


e1 = Event.create(host: u1, activity: a1, coordinate: c1)
e2 = Event.create(host: u2, activity: a2, coordinate: c2)
e3 = Event.create(host: u3, activity: a3, coordinate: c3)
e4 = Event.create(host: u4, activity: a4, coordinate: c4)
e5 = Event.create(host: u5, activity: a5, coordinate: c5)
e6 = Event.create(host: u6, activity: a6, coordinate: c6)
e7 = Event.create(host: u7, activity: a7, coordinate: c7)
e8 = Event.create(host: u8, activity: a8, coordinate: c8)
